import { execFile } from 'node:child_process';
import fs from 'node:fs/promises';
import path from 'node:path';
import { config } from '../config/env.js';
import { Playlist } from '../models/Playlist.js';
import { Schedule } from '../models/Schedule.js';

const PLAYLISTS_DIR = path.join(config.liquidsoapDir, 'playlists');
const RADIO_LIQ_PATH = path.join(config.liquidsoapDir, 'radio.liq');

function playlistM3uPath(playlistId) {
  return path.join(PLAYLISTS_DIR, `${playlistId}.m3u`);
}

function escapeLiquidsoapString(value) {
  return String(value).replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

async function ensureDirs() {
  await fs.mkdir(PLAYLISTS_DIR, { recursive: true });
}

/**
 * Writes the .m3u playlist file for a single Playlist document, pulling
 * fresh track data (metadata from Mongo, not the file's own ID3 tags) from
 * the DB. Liquidsoap's `reload_mode="watch"` picks this up via inotify with
 * no restart required. Safe to call even for a playlist with zero tracks
 * (writes a valid, empty-of-entries #EXTM3U file).
 */
export async function regeneratePlaylistM3u(playlistId) {
  await ensureDirs();
  const playlist = await Playlist.findById(playlistId).populate('tracks.track').lean();
  if (!playlist) return;

  const lines = ['#EXTM3U'];
  for (const entry of playlist.tracks) {
    const track = entry.track;
    if (!track) continue; // defensive: a dangling ref shouldn't crash generation
    const title = escapeLiquidsoapString(track.title);
    const artist = escapeLiquidsoapString(track.artist);
    const absolutePath = path.resolve(config.uploadDir, 'tracks', track.storedFilename);
    lines.push(`annotate:title="${title}",artist="${artist}":${absolutePath}`);
  }

  await fs.writeFile(playlistM3uPath(playlist._id), lines.join('\n') + '\n', 'utf8');
}

/**
 * Regenerates the .m3u for every playlist that contains the given track —
 * used after a Track's own metadata (title/artist) is edited, since the
 * annotate: fields embedded in each .m3u need to reflect the new values.
 */
export async function regeneratePlaylistsContainingTrack(trackId) {
  const playlists = await Playlist.find({ 'tracks.track': trackId }).select('_id').lean();
  await Promise.all(playlists.map((p) => regeneratePlaylistM3u(p._id)));
}

class DefaultPlaylistInvalidError extends Error {
  constructor(message) {
    super(message);
    this.statusCode = 400;
  }
}

async function assertDefaultPlaylistValid() {
  const defaultPlaylist = await Playlist.findOne({ isDefault: true }).lean();
  if (!defaultPlaylist) {
    throw new DefaultPlaylistInvalidError('No default playlist is configured');
  }
  if (!defaultPlaylist.enabled) {
    throw new DefaultPlaylistInvalidError('The default playlist is disabled');
  }
  if (!defaultPlaylist.tracks || defaultPlaylist.tracks.length === 0) {
    throw new DefaultPlaylistInvalidError('The default playlist has no tracks');
  }
  return defaultPlaylist;
}

function buildRadioLiq({ playlists, scheduleEntries, defaultPlaylistId }) {
  const lines = [];
  lines.push('# AUTO-GENERATED by liquidsoapService.regenerateAndRestart() — DO NOT EDIT BY HAND.');
  lines.push(`# Regenerated at: ${new Date().toISOString()}. Any manual edit is overwritten on the`);
  lines.push('# next playlist/schedule structural change.');
  lines.push('');
  lines.push('set("log.file.path", "/var/log/liquidsoap/radio.log")');
  lines.push('set("log.stdout", true)');
  lines.push('');

  const sourceVarFor = (id) => `playlist_${String(id).replace(/[^a-zA-Z0-9]/g, '')}`;

  for (const playlist of playlists) {
    const varName = sourceVarFor(playlist._id);
    const m3uPath = playlistM3uPath(playlist._id);
    lines.push(
      `${varName} = playlist(id="${varName}", mode="normal", reload_mode="watch", "${escapeLiquidsoapString(m3uPath)}")`
    );
  }
  lines.push('');

  const defaultVarName = sourceVarFor(defaultPlaylistId);

  lines.push('radio = switch(track_sensitive=true,');
  lines.push('  [');
  for (const entry of scheduleEntries) {
    const startTs = Math.floor(new Date(entry.startAt).getTime() / 1000);
    const endTs = Math.floor(new Date(entry.endAt).getTime() / 1000);
    const varName = sourceVarFor(entry.playlist);
    // time() returns a float — emit explicit float literals (Liquidsoap's type
    // inference rejects bare ints here, e.g. "1784095200" vs "1784095200.0").
    lines.push(`    (fun () -> (time() >= ${startTs}.0 and time() <= ${endTs}.0), ${varName}),`);
  }
  lines.push(`    (fun () -> true, ${defaultVarName})`);
  lines.push('  ]');
  lines.push(')');
  lines.push('');

  lines.push('output.icecast(%mp3(bitrate=128),');
  lines.push(`  host="${escapeLiquidsoapString(config.icecastHost)}",`);
  lines.push(`  port=${config.icecastPort},`);
  lines.push(`  password="${escapeLiquidsoapString(config.icecastSourcePassword)}",`);
  lines.push(`  mount="${escapeLiquidsoapString(config.icecastMount)}",`);
  lines.push(`  name="${escapeLiquidsoapString(config.stationName)}",`);
  lines.push(`  description="${escapeLiquidsoapString(config.stationDescription)}",`);
  lines.push(`  genre="${escapeLiquidsoapString(config.stationGenre)}",`);
  lines.push(`  url="${escapeLiquidsoapString(config.stationPublicUrl)}",`);
  lines.push('  radio');
  lines.push(')');
  lines.push('');

  return lines.join('\n');
}

async function restartLiquidsoap() {
  if (!config.liquidsoapRestartEnabled) {
    console.log('[liquidsoapService] LIQUIDSOAP_RESTART_ENABLED=false — skipping systemctl restart (dev mode)');
    return;
  }
  await new Promise((resolve, reject) => {
    execFile('sudo', ['/usr/bin/systemctl', 'restart', 'liquidsoap'], (error, stdout, stderr) => {
      if (error) {
        console.error('[liquidsoapService] systemctl restart liquidsoap failed:', stderr || error.message);
        reject(error);
        return;
      }
      resolve();
    });
  });
}

/**
 * Full structural regeneration: validates the default-playlist invariant,
 * re-derives radio.liq from current DB state, ensures every referenced
 * playlist has an up-to-date .m3u, then restarts Liquidsoap. Call this for
 * any change that alters the SET of sources or schedule predicates
 * (playlist created/deleted/enabled-toggled/default-changed, or any
 * Schedule CRUD) — never for track-level edits within an existing,
 * already-declared playlist (use regeneratePlaylistM3u for those, no
 * restart needed).
 */
export async function regenerateAndRestart() {
  await ensureDirs();
  const defaultPlaylist = await assertDefaultPlaylistValid();

  const enabledPlaylists = await Playlist.find({ enabled: true }).lean();
  const now = new Date();
  const scheduleEntries = await Schedule.find({ endAt: { $gt: now } })
    .sort({ startAt: 1 })
    .lean();

  await fs.writeFile(
    RADIO_LIQ_PATH,
    buildRadioLiq({
      playlists: enabledPlaylists,
      scheduleEntries,
      defaultPlaylistId: defaultPlaylist._id,
    }),
    'utf8'
  );

  await Promise.all(enabledPlaylists.map((p) => regeneratePlaylistM3u(p._id)));

  await restartLiquidsoap();
}

/**
 * Same as regenerateAndRestart(), but tolerates the "no valid default
 * playlist yet" case by skipping the regen/restart instead of throwing.
 * Use this for structural changes that aren't themselves about fixing the
 * default-playlist invariant (playlist create/delete/enable-toggle) so a
 * fresh install isn't blocked before the admin has had a chance to create
 * and flag a first default playlist — there's nothing valid to run yet
 * regardless, and the next call to setDefault() (which uses the strict
 * regenerateAndRestart()) will perform the real regen once the invariant
 * can actually hold.
 */
export async function regenerateAndRestartIfConfigured() {
  try {
    await regenerateAndRestart();
    return { skipped: false };
  } catch (err) {
    if (err instanceof DefaultPlaylistInvalidError) {
      console.log(`[liquidsoapService] Skipping regen/restart — ${err.message}`);
      return { skipped: true, reason: err.message };
    }
    throw err;
  }
}

/**
 * Non-throwing version of assertDefaultPlaylistValid(), for status/diagnostic
 * reporting where "no valid default playlist" is a fact to display, not an
 * error to propagate.
 */
export async function getDefaultPlaylistStatus() {
  try {
    await assertDefaultPlaylistValid();
    return { valid: true, reason: null };
  } catch (err) {
    if (err instanceof DefaultPlaylistInvalidError) {
      return { valid: false, reason: err.message };
    }
    throw err;
  }
}

export function getRadioLiqPath() {
  return RADIO_LIQ_PATH;
}

export { DefaultPlaylistInvalidError };
